spring:
  profiles:
    group:
      "local": "local,common"
      "dev":  "dev,common"
      "prod": "prod,common"

---

spring:
  application:
    name: classlink_auth
  main:
    allow-circular-references: true
  config:
    activate:
      on-profile: "common"
  
mybatis:
  type-aliases-package: com.classlink.auth.domain
  mapper-locations: classpath:static/mapper/**/*.xml

---

spring:
  config:
    activate:
      on-profile: "prod"
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
    hikari:
      maximum-pool-size: 10

server: 
  port: 5000
  live: true
  
log:
  config:
    path: /var/app/current
    filename: server-dev
    maxHistory: 7 # 7일
    totalSizeCap: 10MB # 로그 파일 사이즈
  
---


spring:
  config:
    activate:
      on-profile: "dev"
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.171.101.31:45336/classlink?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: classlink
    password: classlink!02$
    hikari:
      maximum-pool-size: 10
      
server: 
  port: 5000
  live: true
  
log:
  config:
    path: /var/app/current
    filename: server-dev
    maxHistory: 7 # 7일
    totalSizeCap: 10MB # 로그 파일 사이즈
---

spring:
  config:
    activate:
      on-profile: "local"
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.171.101.31:45336/classlink?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: classlink
    password: classlink!02$
    hikari:
      maximum-pool-size: 10
server: 
  port: 5000
  live: true
  
log:
  config:
    path: C:\responsFile\Log\classlink
    filename: app-local
    maxHistory: 7 # 7일
    totalSizeCap: 10MB # 로그 파일 사이즈